### ISSUE TITLE
Question regarding abbreviations and preprocessing

### ISSUE THREAD

**Issue by KimBenjaminTang** [BruceWen120/medal#36]
Hello BruceWen!

thanks for your work and making the medal dataset available!

I loaded the dataset and was looking into the most frequently occuring abbreviations from the first 50000 rows and was wondering why the abbreviations all seem rather cryptic:

![grafik](https://github.com/user-attachments/assets/89304462-c7c5-41f9-99f6-c9d7f4741855)

It seems that occurences of "after" were substituted with "T3" in the articles through the reverse-substitution process, but I don't understand where the abbreviation "T3" stems from. 

![grafik](https://github.com/user-attachments/assets/05858a87-f389-458e-a6af-192507497edb)

I found the original publication of the first article in the dataset with the "T3" abbreviation and it does not mention T3 anywhere but just "after", which was then replaced through your procedure.

Publication: https://pubmed.ncbi.nlm.nih.gov/22/

I also noticed that the text in the medal dataset does not contain and punctuation. Why was this removed? The part in your publication where the creation of the medal dataset is presented, does not go into details here.

And you modified abbreviations from prior research and ended up with 5,886 abbreviations in total with corresponding expansions. Is this dataframe/dictionary also available for download?

This is the code I used to reconstruct such abbreviation-expansion dictionary based on the medal dataset now:

```
from tqdm.auto import tqdm 
import pandas as pd

medal_df = pd.read_csv(path_to_full_data_csv)
medal_df.head()

loop_df = medal_df[:50000]
overall_article_abrbeviations_df = pd.DataFrame()

for index, row in tqdm(loop_df.iterrows(), total=len(loop_df)):

    start_positions = [int(x) for x in row["LOCATION"].split("|")]
    resolutions = row["LABEL"].split("|")
    abbreviations = []
    for start in range(len(start_positions)):
        abbreviations.append(row["TEXT"].split(" ")[start_positions[start]])

    this_article_abbreviations_df = pd.DataFrame()
    this_article_abbreviations_df["Abbreviations"]=abbreviations
    this_article_abbreviations_df["Resolutions"]=resolutions
    overall_article_abrbeviations_df = pd.concat([overall_article_abrbeviations_df,this_article_abbreviations_df])
    
abbreviation_df = overall_article_abrbeviations_df.groupby(['Abbreviations', 'Resolutions']).size().sort_values(ascending=False).reset_index(name='count') 
```

I inspected the most frequently occuring and least frequently occuring abbreviations and I suspect that some error happened during the reverse-substitution process for most of the frequently occuring abbreviations:

![grafik](https://github.com/user-attachments/assets/2fcd15e2-4911-492b-849f-3beed21581bb)

Hopefully you can help me understand these things a little bit better :)

**Comment by BruceWen120** [comment]
Hi there, thank you for your interest in our work!

The mappings between abbreviations and expansions can be found in [this file](https://github.com/McGill-NLP/medal/blob/master/toy_data/valid_adam.txt) (I probably should mention this in the README).

About the high-frequency abbreviations, it's possible that some of them are more generic and less specific to medicine, like you noticed, but I don't think that means there's an error in the reverse substitution process. What might have happened was that those mappings are valid as they're established in prior work, but their more-generic expansions are more frequent in the corpus and so they are substituted more frequently. I think it's a valid question to ask whether it'd be better if they are included less frequently than the ones that are less generic, because while they contain less medical knowledge, one can argue that they still appear in medical notes and learning them is helpful for understanding medical notes.

As for punctuations, yes they were removed in the pre-processing and admittedly it's a limitation of this work. If I recall correctly, they were removed because that was required for a model we were developing originally but we didn't end up using that model.

Hope that's helpful, let me know if you have other questions!

**Comment by KimBenjaminTang** [comment]
Hi Bruce, 

thank you so much for the clarifications and link to the file containing the abbreviations and expansions!

I just found out that also the original ADAM database, which you referenced in the publication, is available and had a look at it (https://arrowsmith.psych.uic.edu/arrowsmith_uic/adam.html).

This means the strange looking abbreviations, like "T3", stem from their original work:
![grafik](https://github.com/user-attachments/assets/91455268-5b13-4bd7-9f1b-f28b1b31f9f7)

So I'll have a look at their method to understand it better. :)
